/**
 * CSS do documento premium — fonte única, também usada na exportação HTML.
 * Paleta preto/branco/cinza e dourado só para destaque; muito espaço em branco.
 * Classes com prefixo pg-/premium- para não colidir com o resto do app.
 */
export const PREMIUM_CSS = [
  ".premium-overlay{position:fixed;inset:0;z-index:300;background:#eef0f3;overflow:auto;padding-bottom:60px}",
  ".premium-toolbar{position:sticky;top:0;z-index:2;display:flex;align-items:center;gap:10px;padding:14px 20px;background:rgba(255,255,255,.85);backdrop-filter:saturate(180%) blur(16px);border-bottom:1px solid #e5e7eb}",
  ".premium-toolbar__t{font-size:14px;font-weight:600;color:#111;margin-right:auto}",
  ".premium{--pg-ink:#101114;--pg-mut:#6b7280;--pg-line:#e6e7ea;--pg-gold:#b78b3a;--pg-gold-bg:#faf5ea;max-width:820px;margin:24px auto;padding:0 16px;font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:var(--pg-ink)}",
  ".premium__page{background:#fff;border:1px solid var(--pg-line);border-radius:6px;box-shadow:0 12px 40px rgba(16,17,20,.08);padding:52px 56px;margin-bottom:28px;position:relative;min-height:940px;display:flex;flex-direction:column;-webkit-print-color-adjust:exact;print-color-adjust:exact}",
  ".pg-mark{display:inline-grid;place-items:center;width:30px;height:30px;border-radius:8px;background:#101114;color:#fff;font-weight:700;font-size:15px;flex:0 0 auto}",
  ".pg-logo{display:block;object-fit:contain;flex:0 0 auto;height:auto;width:auto}",
  ".pg-logo--cover{max-height:96px;max-width:260px}",
  ".pg-logo--sign{max-height:60px;max-width:160px}",
  ".pg-eyebrow{font-size:11px;font-weight:600;letter-spacing:.18em;text-transform:uppercase;color:var(--pg-gold)}",
  ".pg-rule{width:44px;height:2px;background:var(--pg-gold);margin:20px 0}",
  ".pg-h2{font-size:30px;font-weight:680;letter-spacing:-.02em;margin:0 0 4px;padding-bottom:14px;position:relative}",
  '.pg-h2::after{content:"";position:absolute;left:0;bottom:0;width:40px;height:3px;background:var(--pg-gold);border-radius:2px}',
  ".pg-foot{margin-top:auto;padding-top:22px;border-top:1px solid var(--pg-line);display:flex;justify-content:space-between;font-size:11px;color:var(--pg-mut);letter-spacing:.02em}",
  ".pg-cover{justify-content:space-between}",
  ".pg-cover__top{display:flex;justify-content:space-between;align-items:center}",
  ".pg-brand{display:flex;align-items:center;gap:10px;font-weight:600;font-size:14px}",
  ".pg-cover__date{font-size:13px;color:var(--pg-mut)}",
  ".pg-cover__mid{padding:40px 0}",
  ".pg-cover__name{font-size:22px;font-weight:600;color:var(--pg-gold);margin-top:14px}",
  ".pg-cover__title{font-size:52px;line-height:1.02;font-weight:700;letter-spacing:-.04em;margin:0}",
  ".pg-cover__sub{font-size:18px;color:var(--pg-mut);margin-top:12px;font-weight:500}",
  ".pg-cover__phrase{font-size:17px;line-height:1.6;color:#3a3b40;max-width:44ch;margin-top:32px;font-style:italic}",
  ".pg-cover__foot{margin-top:auto;font-size:12px;color:var(--pg-mut);letter-spacing:.03em}",
  ".pg-grid4{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:26px 0}",
  ".pg-card{border:1px solid var(--pg-line);border-radius:10px;padding:18px}",
  ".pg-card__ic{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:8px;background:var(--pg-gold-bg);color:var(--pg-gold);margin-bottom:12px}",
  ".pg-card__ic svg{width:19px;height:19px}",
  ".pg-card__lbl{font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--pg-mut)}",
  ".pg-card__val{font-size:16px;font-weight:560;margin-top:4px;line-height:1.35}",
  ".pg-2col{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:8px 0 22px}",
  ".pg-box{border:1px solid var(--pg-line);border-radius:10px;padding:18px 20px}",
  ".pg-box__t{font-size:13px;font-weight:640;margin-bottom:12px;display:flex;align-items:center;gap:8px}",
  ".pg-box p{font-size:14px;line-height:1.6;color:#33343a;margin:0}",
  ".pg-ic{display:inline-flex;color:var(--pg-gold)}.pg-ic svg{width:17px;height:17px}",
  ".pg-check,.pg-dot{list-style:none;margin:0;padding:0;display:grid;gap:9px}",
  ".pg-check li{display:flex;gap:9px;font-size:14px;line-height:1.4;align-items:flex-start}",
  ".pg-tick{display:inline-grid;place-items:center;width:18px;height:18px;border-radius:50%;background:var(--pg-gold-bg);color:var(--pg-gold);flex:0 0 auto;margin-top:1px}",
  ".pg-tick svg{width:12px;height:12px}",
  ".pg-dot li{position:relative;padding-left:16px;font-size:14px;line-height:1.5}",
  '.pg-dot li::before{content:"";position:absolute;left:0;top:8px;width:5px;height:5px;border-radius:50%;background:var(--pg-gold)}',
  ".pg-highlight{background:var(--pg-gold-bg);border:1px solid #efe3c8;border-radius:12px;padding:22px 24px;margin-top:6px}",
  ".pg-highlight__t{font-size:12px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--pg-gold);margin-bottom:10px}",
  ".pg-highlight p{font-size:14.5px;line-height:1.65;color:#33343a;margin:0}",
  ".pg-blocks{display:grid;gap:14px;margin:24px 0}",
  ".pg-block{border:1px solid var(--pg-line);border-radius:10px;padding:18px 20px}",
  ".pg-block__h{font-size:13px;font-weight:640;display:flex;align-items:center;gap:9px}",
  ".pg-block__ic{display:inline-grid;place-items:center;width:28px;height:28px;border-radius:7px;background:#101114;color:#fff}",
  ".pg-block__ic svg{width:16px;height:16px}",
  ".pg-block__v{font-size:16px;font-weight:560;margin-top:10px}",
  ".pg-block__d{font-size:13.5px;color:var(--pg-mut);margin-top:6px;line-height:1.5}",
  ".pg-badges{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}",
  ".pg-badge{font-size:11.5px;font-weight:560;padding:4px 10px;border-radius:999px;border:1px solid var(--pg-gold);color:var(--pg-gold)}",
  ".pg-timeline{margin-top:8px;border:1px solid var(--pg-line);border-radius:12px;padding:22px 24px}",
  ".pg-timeline__t{font-size:12px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--pg-mut);margin-bottom:18px}",
  ".pg-tl{display:flex;gap:14px;padding-bottom:20px;position:relative}",
  ".pg-tl:last-child{padding-bottom:0}",
  '.pg-tl::before{content:"";position:absolute;left:6px;top:14px;bottom:-6px;width:2px;background:var(--pg-line)}',
  ".pg-tl:last-child::before{display:none}",
  ".pg-tl__dot{width:14px;height:14px;border-radius:50%;border:3px solid var(--pg-gold);background:#fff;flex:0 0 auto;margin-top:2px;z-index:1}",
  ".pg-tl__lbl{font-size:14.5px;line-height:1.4}.pg-tl__lbl b{display:block;font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--pg-gold);margin-bottom:2px;font-weight:600}",
  ".pg-check-inline__lead{font-size:13.5px;color:#33343a;margin-bottom:12px}",
  ".pg-check-inline{display:flex;flex-wrap:wrap;gap:8px}",
  ".pg-chip{display:inline-flex;align-items:center;gap:7px;font-size:13px;font-weight:500;padding:7px 13px;border-radius:999px;background:#fff;border:1px solid var(--pg-line)}",
  ".pg-muted{font-size:13px;color:var(--pg-mut);margin-top:14px}",
  ".pg-close__msg{font-size:18px;line-height:1.7;font-weight:500;margin:18px 0 0;max-width:52ch}",
  ".pg-close__commit{font-size:15px;line-height:1.7;color:#3a3b40;font-style:italic;margin:24px 0;max-width:52ch}",
  ".pg-sign{display:flex;align-items:center;gap:12px;margin-top:10px;padding-top:22px;border-top:1px solid var(--pg-line)}",
  ".pg-sign b{display:block;font-size:15px}.pg-sign span{font-size:12.5px;color:var(--pg-mut)}",
  ".pg-contacts{display:flex;flex-wrap:wrap;gap:18px;margin-top:18px;font-size:13.5px;color:#33343a}",
  ".pg-contacts span{display:inline-flex;align-items:center;gap:7px}",
  ".pg-qrs{display:flex;gap:28px;margin-top:26px}",
  ".pg-qr{text-align:center}",
  ".pg-qr__img{border:1px solid var(--pg-line);border-radius:8px;padding:6px;background:#fff}",
  ".pg-qr__ph{display:grid;place-items:center;border:1px dashed var(--pg-line);border-radius:8px;color:var(--pg-mut);font-size:12px}",
  ".pg-qr__lbl{font-size:12px;color:var(--pg-mut);margin-top:8px;font-weight:500}",
  ".pg-flow{min-height:0}",
  ".pg-report__lead{margin:20px 0 6px}",
  ".pg-report__lead .pg-report__p{font-size:15px;color:#2a2b30;line-height:1.7}",
  ".pg-report__sec{margin-top:22px;padding-top:20px;border-top:1px solid var(--pg-line)}",
  ".pg-report__sec:first-of-type{border-top:none;padding-top:0}",
  ".pg-report__t{font-size:17px;font-weight:640;letter-spacing:-.01em;margin:0 0 10px;break-after:avoid;page-break-after:avoid}",
  ".pg-report__p{font-size:14px;line-height:1.65;color:#33343a;margin:0 0 10px}",
  ".pg-report__p:last-child{margin-bottom:0}",
  ".pg-report__list{list-style:none;margin:6px 0 10px;padding:0;display:grid;gap:8px}",
  ".pg-report__list li{display:flex;gap:9px;font-size:14px;line-height:1.5;align-items:flex-start;color:#33343a}",
  "@media (max-width:640px){.premium__page{padding:30px 24px;min-height:0}.pg-grid4,.pg-2col{grid-template-columns:1fr}.pg-cover__title{font-size:38px}}",
  "@media print{body>*:not(.premium-portal){display:none !important}.premium-portal{position:static}.premium-overlay{position:static;background:#fff;padding:0;overflow:visible}.premium-toolbar{display:none}.premium{max-width:none;margin:0;padding:0}.premium__page{box-shadow:none;border:none;border-radius:0;margin:0;min-height:auto;padding:16mm;page-break-after:always}.premium__page:last-child{page-break-after:auto}@page{size:A4;margin:0}}",
].join("\n");
